source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.1'

use_frameworks!
target 'FBSnapshotTestCaseDemoTests' do
  pod 'Specta'
  pod 'Expecta+Snapshots', :path => "../"
  pod 'iOSSnapshotTestCase', git: 'https://github.com/smoothdvd/ios-snapshot-test-case.git'
end
